CREATE TABLE CLIENT(
 ID   INT    NOT NULL,
 FIRST_NAME  VARCHAR (30)     NOT NULL,
 LAST_NAME   VARCHAR (30)     NOT NULL,
 AGE  INT  NOT NULL,
 ADDRESS  CHAR (60) ,
 PHONE INT  NOT NULL,
 EMAIL VARCHAR (30) NOT NULL,    
PRIMARY KEY (ID)
);
