CREATE TABLE MEETING(
 MEETING_ID   INT    NOT NULL auto_increment,
 CLIENT_ID  INT      NOT NULL,
 MEETING_TOPIC   VARCHAR (100)     NOT NULL,
 MEETING_DATE DATE,
 MEETING_TIME TIME,
 NUMBER_PEOPLE INT,
FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID),  
PRIMARY KEY (MEETING_ID)
);
